[platformio]
name = TDSTMPSensor
default_envs = WEMOS_D1_Mini
src_dir = src/TDSTMPSensor

[env:WEMOS_D1_Mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_speed = 115200
upload_speed = 115200
custom_fw_version_base = 1.0
extra_scripts = pre:scripts/bump_version.py

board_build.ldscript = eagle.flash.4m2m.ld
board_build.filesystem = littlefs

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DNDEBUG
    -DMQTT_MAX_PACKET_SIZE=1024

lib_deps =
    tzapu/WiFiManager@^2.0.17
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
    ayushsharma82/ElegantOTA@^2.2.9
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.4
